name: Trigger CI in Automation Repository
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Disparar evento en el repositorio de automatización
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/daimilamoru/MyProjectWithCICD/actions/workflows/cipipeline.yml/dispatches \
               -d '{"ref":"main"}'
